# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

on:
  workflow_dispatch:
  push:
    branches:
    - main
  
jobs:
  build_job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.x'
      
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v1.1.1
        id: version
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml
      
      - name: Show Version
        run: |
          echo ${{ env.semVer }}
      
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Restore
        run: dotnet restore
      
      - name: Compile
        run: dotnet build --configuration Release --no-restore
      
      - name: Test
        run: dotnet test

      - name: Publish
        run: dotnet publish --configuration Release -p:Version=${{ env.semVer }} -o ${{ github.workspace }}/output

      - name: List builded files
        run: ls ${{ github.workspace }}/output

      - name: Pack to nuget
        run: dotnet pack --configuration Release --no-restore --no-build --include-symbols --artifacts-path ${{ github.workspace }}/output -o ${{ github.workspace }}/artifacts

      - name: List packed files
        run: ls ${{ github.workspace }}/artifacts